import os

DIST = "dist"

def ensure_dist():
    if not os.path.exists(DIST):
        os.makedirs(DIST)

def generate_css():
    return """
body {
    font-family: Arial, sans-serif;
    background: #111;
    color: white;
    text-align: center;
    padding-top: 100px;
}
"""

def generate_js():
    return """
document.addEventListener("DOMContentLoaded", function() {
    console.log("Page loaded");
});
"""

def generate_html():
    return """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Python Generated Site</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>Hello. Generated by Python.</h1>
    <script src="app.js"></script>
</body>
</html>
"""

def write_file(name, content):
    with open(os.path.join(DIST, name), "w", encoding="utf-8") as f:
        f.write(content)

if __name__ == "__main__":
    ensure_dist()
    write_file("index.html", generate_html())
    write_file("style.css", generate_css())
    write_file("app.js", generate_js())